name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 12.x

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Lint
        run: npm run lint
        env:
          CI: true

      - name: Test
        run: npm run test --ci --coverage --maxWorkers=2
        env:
          TEST_LOGIN: ${{ secrets.TEST_LOGIN }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          CI: true

      - name: Upload Coverage
        run: ./node_modules/.bin/codecov --token="$CODECOV_TOKEN"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Publish
        run: npm publish || true
        env:
         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
